name: Java CI - Lucee 6.0

on: 
  push:
    branches:
      - '**' # thus ignoring tagging
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      luceeVersion: light-6.0.0.451-BETA
      luceeVersionQuery: 6.0/all/light
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: lucee-script-runner-maven-cache
    - name: Cache Lucee files
      uses: actions/cache@v4
      with:
        path: ~/work/_actions/lucee/script-runner/main/lucee-download-cache
        key: lucee-downloads
    - name: Build with Ant
      run: ant -noinput -verbose -buildfile build.xml
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pdf-lex
        path: dist/*.lex
    - name: Checkout Lucee
      uses: actions/checkout@v4
      with:
        repository: lucee/lucee
        path: lucee
    - name: Run Lucee Test Suite
      uses: lucee/script-runner@main
      with:
        webroot: ${{ github.workspace }}/lucee/test
        execute: /bootstrap-tests.cfm
        luceeVersion: ${{ env.luceeVersion }}
        luceeVersionQuery: ${{ env.luceeVersionQuery }}
        extensionDir: ${{ github.workspace }}/dist
        extensions: B737ABC4-D43F-4D91-8E8E973E37C40D1B # image-ext for tests
      env:
        testLabels: pdf
        testAdditional: ${{ github.workspace }}/tests
